name: com.orbital.demos/fhir-api
version: 1.0.0
sourceRoot: src/
additionalSources: {
  "@orbital/openapi" = "openapi/*.yaml"
  "@orbital/nebula" = "nebula/*.nebula.kts"
  "@orbital/config" = "orbital/*.conf"
}
dependencies: {
  
}
compilerOptions: {
  duplicateDefinitionSeverity: DISABLED
}