package com.orbitalhq.demos.xml.films

import kotlin.random.Random

object FilmData {
   val titles = listOf(
      "ACADEMY DINOSAUR",
      "ACE GOLDFINGER",
      "ADAPTATION HOLES",
      "AFFAIR PREJUDICE",
      "AFRICAN EGG",
      "AGENT TRUMAN",
      "AIRPLANE SIERRA",
      "AIRPORT POLLOCK",
      "ALABAMA DEVIL",
      "ALADDIN CALENDAR",
      "ALAMO VIDEOTAPE",
      "ALASKA PHANTOM",
      "DATE SPEED",
      "ALI FOREVER",
      "ALICE FANTASIA",
      "ALIEN CENTER",
      "ALLEY EVOLUTION",
      "ALONE TRIP",
      "ALTER VICTORY",
      "AMADEUS HOLY",
      "AMELIE HELLFIGHTERS",
      "AMERICAN CIRCUS",
      "AMISTAD MIDSUMMER",
      "ANACONDA CONFESSIONS",
      "ANALYZE HOOSIERS",
      "ANGELS LIFE",
      "ANNIE IDENTITY",
      "ANONYMOUS HUMAN",
      "ANTHEM LUKE",
      "ANTITRUST TOMATOES",
      "ANYTHING SAVANNAH",
      "APACHE DIVINE",
      "APOCALYPSE FLAMINGOS",
      "APOLLO TEEN",
      "ARABIA DOGMA",
      "ARACHNOPHOBIA ROLLERCOASTER",
      "ARGONAUTS TOWN",
      "ARIZONA BANG",
      "ARK RIDGEMONT",
      "ARMAGEDDON LOST",
      "ARMY FLINTSTONES",
      "ARSENIC INDEPENDENCE",
      "ARTIST COLDBLOODED",
      "ATLANTIS CAUSE",
      "ATTACKS HATE",
      "ATTRACTION NEWTON",
      "AUTUMN CROW",
      "BABY HALL",
      "BACKLASH UNDEFEATED",
      "BADMAN DAWN",
   )

   val films = titles.mapIndexed { index, title ->
      Film(index.toString(), title, Random.nextInt(1970, 2023))
   }

   val movieAwards = listOf(
      "Best Actor",
      "Best Actress",
      "Best Supporting Actor",
      "Best Supporting Actress",
      "Best Director",
      "Best Original Screenplay",
      "Best Adapted Screenplay",
      "Best Cinematography",
      "Best Film Editing",
      "Best Production Design",
      "Best Costume Design",
      "Best Makeup and Hairstyling",
      "Best Visual Effects",
      "Best Sound Editing",
      "Best Sound Mixing",
      "Best Original Score",
      "Best Original Song",
      "Best Animated Feature",
      "Best Documentary Feature",
      "Best International Film",
      "Best Action Choreography",
      "Best Original Score for a Comedy",
      "Best Original Score for a Drama",
      "Best Voice Over Performance",
      "Best Animated Short Film",
      "Best Live Action Short Film",
      "Best Ensemble Cast",
      "Best Breakthrough Performance",
      "Best Stunt Coordination",
      "Best Film"
   ).map { Award(it, 2020) }

   val actors = listOf(
      "PENELOPE GUINESS",
      "NICK WAHLBERG",
      "ED CHASE",
      "JENNIFER DAVIS",
      "JOHNNY LOLLOBRIGIDA",
      "BETTE NICHOLSON",
      "GRACE MOSTEL",
      "MATTHEW JOHANSSON",
      "JOE SWANK",
      "CHRISTIAN GABLE",
      "ZERO CAGE",
      "KARL BERRY",
      "UMA WOOD",
      "VIVIEN BERGEN",
      "CUBA OLIVIER",
      "FRED COSTNER",
      "HELEN VOIGHT",
      "DAN TORN",
      "BOB FAWCETT",
      "LUCILLE TRACY",
      "KIRSTEN PALTROW",
      "ELVIS MARX",
      "SANDRA KILMER",
      "CAMERON STREEP",
      "KEVIN BLOOM",
      "RIP CRAWFORD",
      "JULIA MCQUEEN",
      "WOODY HOFFMAN",
      "ALEC WAYNE",
      "SANDRA PECK",
      "SISSY SOBIESKI",
      "TIM HACKMAN",
      "MILLA PECK",
      "AUDREY OLIVIER",
      "JUDY DEAN",
      "BURT DUKAKIS",
      "VAL BOLGER",
      "TOM MCKELLEN",
      "GOLDIE BRODY",
      "JOHNNY CAGE",
      "JODIE DEGENERES",
      "TOM MIRANDA",
      "KIRK JOVOVICH",
      "NICK STALLONE",
      "REESE KILMER",
      "PARKER GOLDBERG",
      "JULIA BARRYMORE",
      "FRANCES DAY-LEWIS",
      "ANNE CRONYN",
      "NATALIE HOPKINS",
      )      .mapIndexed { index, name ->
         Actor(index.toString(), name)
   }

}
