version: "3.3"

services:
   demo-services:
      image: ghcr.io/orbitalapi/demos-composing-apis
      ports:
         - "7033:7033"

   orbital:
      image: orbitalhq/orbital:${ORBITAL_VERSION:-next}
      environment:
         JAVA_OPTS: >-
            -Xms256m
            -Xmx2048m
         OPTIONS: >-
            --vyne.analytics.persistRemoteCallResponses=true
            --vyne.analytics.persistResults=true
            --vyne.db.username=orbital
            --vyne.db.password=changeme
            --vyne.db.host=postgres
            --vyne.workspace.project-file=/opt/service/workspace/taxi.conf
      ports:
         - "9022:9022" # http
         - "7655:7655" # rsocket
      volumes:
         - ~/.orbital/license/:/opt/var/vyne/license/
         - ./taxi:/opt/service/workspace
      depends_on:
         - postgres
      deploy:
         resources:
            limits:
               memory:  1500mb
   postgres:
      image: postgres:15
      expose:
         - 5432
      ports:
         - "25432:5432"
      environment:
         POSTGRES_DB: pagila
         POSTGRES_USER: root
         POSTGRES_PASSWORD: admin
      volumes:
         - postgres_data:/var/lib/postgresql/data
         - ./db:/docker-entrypoint-initdb.d

volumes:
   postgres_data:
