name: com.acme/large-estate-demo
version: 0.1.0
sourceRoot: src/
additionalSources: {
  "@orbital/openapi" : "openapi/*.yaml",
  "@orbital/config" : "orbital/config/*.conf",
  "@orbital/nebula" : "orbital/nebula/*.nebula.kts"
  "@orbital/function-kts" : "functions/*.taxi.kts"
}
