jdbc {
    databricks-risk {
        connectionName=databricks-risk
        connectionParameters {
            database="databricks_pg"
            host=nebula
            password=test
            port=${NEBULA_DATABRICKS_PG_PORT}
            username=test
        }
        jdbcDriver=POSTGRES
    }
    snowflake-claims {
        connectionName=snowflake-claims
        connectionParameters {
            database="snowflake_pg"
            host=nebula
            password=test
            port=${NEBULA_SNOWFLAKE_PG_PORT}
            username=test
        }
        jdbcDriver=POSTGRES
    }
}

