server.port: 9981
spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      group-id: films-producer
  cloud:
    config:
      enabled: false
  application:
    name: films-service

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,info,health,loggers

springdoc:
   pathsToMatch: /films/**
