version: "3.3"

services:
   orbital:
      image: orbitalhq/orbital:${ORBITAL_VERSION:-latest}
      environment:
         JAVA_OPTS: >-
            -Xms256m
            -Xmx1024m
         OPTIONS: >-
            --vyne.analytics.persistRemoteCallResponses=true
            --vyne.analytics.persistResults=true
            --vyne.db.username=orbital
            --vyne.db.password=changeme
            --vyne.db.host=postgres
            --vyne.workspace.config-file=/opt/service/workspace/workspace.conf
      ports:
         - "9022:9022"
      expose:
         - 9022
      volumes:
         - ~/.orbital/license/:/opt/var/vyne/license/
         - .:/opt/service/workspace
      depends_on:
         - postgres
      deploy:
         resources:
            limits:
               memory: 2gb

   postgres:
      image: postgres:15
      expose:
         - 5432
      ports:
         - "25432:5432"
      environment:
         POSTGRES_DB: orbital
         POSTGRES_USER: orbital
         POSTGRES_PASSWORD: changeme
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
